# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
tensor_0 = torch.randn(size=(7, 7))
tensor_0
tensor_0.shape

torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [10]:
# Create another random tensor
tensor_1 = torch.randn(size=(1,7))
# Perform matrix multiplication 
tensor_2 = torch.matmul(tensor_0, tensor_1.T)
tensor_2, tensor_2.shape

(tensor([[ 1.5864],
         [-0.9821],
         [-0.0673],
         [-1.6436],
         [-0.6995],
         [ 1.1095],
         [-0.5288]]), torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_3 = torch.randn(size=(7,1))
tensor_4 = torch.randn(size=(1,7))
# Matrix multiply tensors
tensor_5 = torch.matmul(tensor_3, tensor_4)
tensor_5, tensor_5.shape

(tensor([[ 1.2914, -1.1084, -0.6216, -0.9194,  0.2805, -1.3201,  1.6960],
         [-0.2459,  0.2111,  0.1184,  0.1751, -0.0534,  0.2514, -0.3229],
         [-1.8259,  1.5671,  0.8788,  1.2999, -0.3966,  1.8665, -2.3980],
         [ 0.4764, -0.4088, -0.2293, -0.3391,  0.1035, -0.4870,  0.6256],
         [-0.9089,  0.7801,  0.4374,  0.6471, -0.1974,  0.9291, -1.1936],
         [-1.1721,  1.0060,  0.5641,  0.8345, -0.2546,  1.1981, -1.5393],
         [ 0.3380, -0.2901, -0.1627, -0.2407,  0.0734, -0.3455,  0.4439]]),
 torch.Size([7, 7]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [17]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Create two random tensors on GPU
tensor_6 = torch.randn(size=(2,3)).to(device)
tensor_7 = torch.randn(size=(2,3)).to(device)

tensor_6, tensor_7

(tensor([[ 0.0461,  0.4024, -1.0115],
         [ 0.2167, -0.6123,  0.5036]], device='cuda:0'),
 tensor([[ 0.2310,  0.6931, -0.2669],
         [ 2.1785,  0.1021, -0.2590]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [20]:
# Perform matmul on tensor_A and tensor_B
tensor_8 = torch.matmul(tensor_6, tensor_7.T)
tensor_8, tensor_8.shape

(tensor([[ 0.5595,  0.4036],
         [-0.5087,  0.2792]], device='cuda:0'), torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [21]:
# Find max
max_value = torch.max(tensor_8)
# Find min
min_value = torch.min(tensor_8)

max_value, min_value

(tensor(0.5595, device='cuda:0'), tensor(-0.5087, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [22]:
# Find arg max
arg_max = torch.argmax(tensor_8)

# Find arg min
arg_min = torch.argmin(tensor_8)

arg_max, arg_min

(tensor(0, device='cuda:0'), tensor(2, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_9 = torch.randn(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_10 = tensor_9.squeeze()

# Print out tensors and their shapes
tensor_9, tensor_9.shape, tensor_10, tensor_10.shape

(tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
             1.2324,  0.1382, -1.6822]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
          0.1382, -1.6822]),
 torch.Size([10]))